pangeo-data/climpred

- esmtools/vis.py
* Actually return gl object for make_cartopy
* Return axes and colorbar objects for quick_pcolor
> Edits to vis submodule

- CHANGES.txt
- LICENSE.txt
- esmtools/prediction.py
- esmtools/stats.py
- notebooks/stats_demo_and_test.ipynb
This PR cleans up the stats module by removing redundant functions, improving documentation, and adding some functionality to current functions.
> Update stats module

- climpred/stats.py
Removes 
xr_cos_weight
xr_area_weight
xr_smooth_series
xr_linregress
create_power_spectrum (maybe delete for now, I took it into my repo)
_taper
> remove unnecessary stats functions

- .travis.yml
- ci/requirements-py36.yml
- setup.py
> Introduce CI

- ci/requirements-py36.yml
- setup.py
@bradyrx please merge this PR before relative entropy
> add ci eofs

- .travis.yml
- ci/requirements-py36.yml
Add any points to discuss in the PR thread. Issues with the code? Suggestions needed? Philosophy changes to the package?
Please add any references to manuscripts, textbooks, etc.
> Update travis so it works properly

- climpred/classes.py
- climpred/prediction.py
- climpred/stats.py
- climpred/tests/test_utils.py
- climpred/utils.py
Clean up function calls with a decorator
https://github.com/bradyrx/climpred/issues/95
> Replace check_xarray as a decorator

- climpred/loadutils.py
This adds a `proxy_dict` argument for `open_dataset()` for folks on servers with firewalls. This allows me to load the datasets at LANL for instance. Probably won't be used by many, but good to have the option.
Tried `open_dataset()` on LANL computer without the proxy argument and get a long error, ending in:
Tried again while inputting the LANL proxyout and the dataset loads:
-   [x]  I have squashed commits to a reasonable amount, and force-pushed the squashed commits.
-   [x]  All notebooks run with this branch; tested via …
> Add proxy option for open_dataset

- climpred/prediction.py
- climpred/stats.py
- climpred/tests/test_utils.py
Turns out I didn't call the decorators properly in places and also some functions with check_xarray still existed.
Also added a test for classes
https://github.com/bradyrx/climpred/issues/140
> Cleanup check_xarray decorators

- climpred/__init__.py
- climpred/bootstrap.py
- climpred/classes.py
- climpred/comparisons.py
- climpred/exceptions.py
- climpred/graphics.py
- climpred/metrics.py
- climpred/prediction.py
- climpred/stats.py
- climpred/tests/test_hindcast_prediction.py
- climpred/tests/test_stats.py
- climpred/utils.py
Same as in https://github.com/bradyrx/climpred/pull/134, but had to restart it due to the repo cleanup. This PR will add a few custom exceptions for more clear error reporting.
Fixes # https://github.com/bradyrx/climpred/issues/111 (not entirely, but down this line)
```python
import climpred as cp
hind = cp.loadutils.open_dataset('CESM-DP-SST')
hist = cp.loadutils.open_dataset('CESM-LE')
hist = hist.isel(member=0)
print(hist)
<xarray.Dataset>
Dimensions:  (time: 61)
Coordinates:
* time     (time) int64 1955 1956 1957 1958 1959 ... 2011 2012 2013 2014 2015
Data variables:
SST      (time) float64 ...
cp.bootstrap.bootstrap_uninitialized_ensemble(hind, hist)
``` …
> Add custom exceptions for clearer error reporting.

- climpred/__init__.py
- climpred/bootstrap.py
- climpred/classes.py
- climpred/comparisons.py
- climpred/exceptions.py
- climpred/graphics.py
- climpred/loadutils.py
- climpred/metrics.py
- climpred/prediction.py
- climpred/relative_entropy.py
- climpred/stats.py
- climpred/tests/test_comparisons.py
- climpred/tests/test_graphics.py
- climpred/tests/test_hindcast_prediction.py
- climpred/tests/test_perfect_model_prediction.py
- climpred/tests/test_relative_entropy.py
- climpred/tests/test_stats.py
- climpred/tests/test_utils.py
- climpred/utils.py
This uses `black` and `flake8` to apply a standard code style to our repo. This is in preparation for the introduction of `pre-commit` to handle formatting at commit-time when submitting PR's. 
Fixes # https://github.com/bradyrx/climpred/issues/153, https://github.com/bradyrx/climpred/issues/125
> Beautify with black/flake8

- .isort.cfg
- .pre-commit-config.yaml
- .travis.yml
- README.md
- ci/requirements-py36.yml
- ci/run-linter.sh
- climpred/__init__.py
- climpred/bootstrap.py
- climpred/classes.py
- climpred/comparisons.py
- climpred/graphics.py
- climpred/metrics.py
- climpred/prediction.py
- climpred/relative_entropy.py
- climpred/stats.py
- climpred/tests/test_demo_data.py
- climpred/tests/test_hindcast_prediction.py
- climpred/tests/test_perfect_model_prediction.py
- climpred/tests/test_stats.py
- climpred/tests/test_utils.py
- climpred/tutorial.py
- setup.py
This PR adds `pre-commit` for contributors. This forces a common style to all commits and does flake8 checks at commit-time. 
@aaronspring, @ahuang11, make sure to install `pre-commit` for future contributions. `pip install pre-commit` then `pre-commit install` in the main directory.
Fixes # https://github.com/bradyrx/climpred/issues/153, https://github.com/bradyrx/climpred/issues/125
Added some commits with pre-commit and it ran just fine.
> Add pre-commit hooks and contribution guide.

- README.md
- climpred/bootstrap.py
- climpred/graphics.py
- climpred/prediction.py
- climpred/stats.py
- climpred/tests/test_demo_data.py
- climpred/tests/test_graphics.py
- climpred/tests/test_hindcast_prediction.py
- climpred/tests/test_perfect_model_prediction.py
- climpred/tests/test_relative_entropy.py
- climpred/tests/test_stats.py
quick fixes: add new tests to increase coverage
(first try with pre-commit pipeline)
Fixes https://github.com/bradyrx/climpred/issues/137
-   [ ]  I have squashed commits to a …
> increase converage

- README.md
- climpred/bootstrap.py
- climpred/tests/test_perfect_model_prediction.py
- p_values were wrong if positively oriented
- gitter bagde
-   [x]  I have squashed commits to a reasonable amount, and force-pushed the squashed commits.
-   [x]  All notebooks run with this branch; tested via `treon`.
-   [x]  `pytest` runs without breaking.
> add gitter bagde, bugfix bootstrap

- .travis.yml
- ci/docs.yml
- ci/environment-dev-3.6.yml
Test to see if we can add docs build to CI. readthedocs currently doesn't work on PRs. This is a way to check if the docs build alright with additions.
> Add doc build to CI

- climpred/stats.py
Previously, `rm_poly` looked for specific NaN cases to avoid the computational expense of interpolating NaNs. However, use of `if` `elif` `else` only made one case work. So all NaNs were being forward-filled.
This makes it so that appropriate cases are forward-filled, back-filled, and interpoalted.
-   [X]  Bug fix (non-breaking change which fixes an issue)
```python
A = [ [np.nan, 1, 2, 3], [1, 2, 3, np.nan], [1, 2, np.nan, 3] ]
A = xr.DataArray(A, dims=['lat', 'time'])
B = [ [1, 1, 2, 3], [1, 2, 3, 3], [1, 2, 2.5, 3] ]
B = xr.DataArray(B, dims=['lat', 'time'])
```
*Old Version:*
```python
from climpred.stats import rm_trend
rm_trend(A)
<xarray.DataArray (lat: 3, time: 4)>
array([[ nan, -0.4, -0.1,  0.2],
[-0.8,  0.4,  1.6,  nan],
[-0.2,  0.1, …
```
> Fixes to rm_poly

- HOWTORELEASE.rst
- README.rst
- docs/source/index.rst
- docs/source/release_procedure.rst
Adds `pip install climpred` to README as well as the PyPI release procedure.
> add pip install to README

- README.rst
- docs/source/index.rst
Adds some badges to the README and readthedocs.
> Add PyPI and license badges; fix travis badge

- CHANGELOG.rst
- HOWTORELEASE.rst
- README.rst
- docs/source/index.rst
This adds our new `conda-forge` channel.
> Add conda badge and install instructions

- docs/source/metrics.rst
Fixes small typo in docs in the custom metric section.
> fix typo in custom metrics

- CHANGELOG.rst
- ci/environment-dev-3.6.yml
- requirements.txt
Updates requirements to `xskillscore v0.0.12` to get 30-50% speedup in compute functions.
> Upgrade to xskillscore 0.0.12 for speedup on compute functions

- CHANGELOG.rst
- climpred/bootstrap.py
- climpred/comparisons.py
- climpred/constants.py
- climpred/prediction.py
- removed `to_be_shuffled` in bootstrap
- add `concat_kwargs`
- remove member dim in coords in `m2c` comparison and cleanup in bootstrap
- renamed `ds` to `init_pm` where initialized from PM …
> As bootstrap from control cftime

- climpred/bootstrap.py
- climpred/prediction.py
- climpred/tests/test_hindcast_prediction.py
- climpred/tests/test_perfect_model_prediction.py
- climpred/utils.py
> metadata persistence

- docs/source/publications.rst
Adds official citations to @aaronspring and @bradyrx publications using `climpred`.
Closes https://github.com/bradyrx/climpred/issues/357
> update Aaron and Riley's publications

- climpred/bootstrap.py
-   [ ]  refactoring
Please describe the tests that you ran to verify your changes. This could point to a cell in the updated notebooks. Or a snippet of code with accompanying figures …
> fix issue by compute

- climpred/bootstrap.py
-   [ ]  refactoring
Please describe the tests that you ran to verify your changes. This could point to a cell in the updated notebooks. Or a snippet of code with accompanying figures …
> Pr 355/bradyrx/as bootstrap metric refactor

- CHANGELOG.rst
- climpred/classes.py
- climpred/tests/test_PredictionEnsemble_math.py
Closes #248 
-   [x]  This change requires a documentation update
pytest
-   [ ]  I have updated the sphinx documentation, if necessary.
-   [ ]  I have squashed commits to a reasonable amount, and force-pushed the squashed …
> implement math +-*/ for PredictionEnsemble

- CHANGELOG.rst
- ci/environment-dev-3.6.yml
- climpred/classes.py
- climpred/comparisons.py
- climpred/tests/test_hindcastEnsemble_class.py
- requirements.txt
> As hist m2o bug

- HOWTOCONTRIBUTE.rst
See https://github.com/raybellwaves/xskillscore/issues/116
> DOC: update pip with no deps

- CHANGELOG.rst
- README.rst
- docs/source/index.rst
- setup.py
Changes the tagline/punchline for `climpred` to be more broader in scope and confident in capability. 
Closes https://github.com/bradyrx/climpred/issues/412
> change tagline

- .github/ISSUE_TEMPLATE/config.yml
This adds a "General Question" template for the issues that links to our gitter. `xarray` links this to their stackoverflow tag.
> add general question queue

- CONTRIBUTING.md
- README.rst
- asv_bench/asv.conf.json
- climpred/tutorial.py
- docs/requirements.txt
- docs/source/conf.py
- docs/source/contributors.rst
- docs/source/index.rst
- docs/source/quick-start.ipynb
- requirements.txt
- setup.py
Converting over any reference to `github.com/bradyrx/climpred` to `github.com/pangeo-data/climpred`.
> New GitHub reference

- climpred/graphics.py
- climpred/metrics.py
- climpred/relative_entropy.py
- climpred/tests/test_metrics_perfect.py
- setup.cfg
Closes #333 
remaining tests: unsure how important? ignore for now
> reduce warnings

- .github/workflows/climpred_testing.yml
Try manually running `git checkout HEAD` on checkout action. This will checkout the current branch.
> try checking out HEAD

- .github/workflows/climpred_installs.yml
- .github/workflows/climpred_testing.yml
- .github/workflows/lint.yml
Trying `${{ github.head_ref }}` and `${{ github.ref }}` to see if it will check out the right repo with forked PRs.
> update repository ref

- .github/workflows/climpred_installs.yml
- .github/workflows/climpred_testing.yml
- .github/workflows/lint.yml
Changes to `${{ github.repository}}` checkout to hopefully work on forked branches.
> change ref

- CHANGELOG.rst
- ci/requirements/climpred-dev.yml
- ci/requirements/minimum-tests.yml
- climpred/bootstrap.py
Closes #479 
-   [ ]  I have squashed commits to a reasonable amount, and force-pushed the …
> use xr.broadcast instead of isel([0]*iterations)

- climpred/stats.py
- climpred/tests/test_stats.py
- docs/source/examples/decadal/diagnose-potential-predictability.ipynb
- requirements.txt
rm test for multiple dims. not needed because varweighted mean period only applicable for time dim
Closes: xrft version fixed
Please describe the tests that you ran to verify your changes. This could point to a cell in the updated notebooks. Or a …
> Test xrft recent?

- .github/workflows/python-publish.yml
- HOWTORELEASE.rst
- README.rst
Haven't figured out how to automate updating stable branch yet. Reverted instructions back to doing it manually.
> fix release instructions

- .pre-commit-config.yaml
Please describe the tests that you ran to verify your …
> update link for black

- .github/workflows/climpred_testing.yml
- ci/requirements/climpred-dev.yml
- ci/requirements/minimum-tests.yml
- climpred/classes.py
- climpred/smoothing.py
- climpred/tests/test_smoothing.py
Updates `setup-miniconda` from `v1` to `v2` due to changes to Github Actions that went into effect today. See https://github.com/conda-incubator/setup-miniconda/issues/101.
> update miniconda version in CI

- README.rst
- docs/source/index.rst
Quick fix to badges. Drop Travis, get license link to proper location, and hopefully fix codecov.
See https://github.com/xarray-contrib/xskillscore/issues/222.
> fix badges

- CHANGELOG.rst
- climpred/graphics.py
> fix plot for composite lead units

- .github/workflows/climpred_installs.yml
- .github/workflows/climpred_testing.yml
- .github/workflows/lint.yml
Remove secrets from ci after email 
Closes #(issue) security issue
#537 shows that the the windows install error has a different cause
Please describe the tests that you ran to verify your changes. This could point to a cell in the updated notebooks. …
> Remove secrets

- .github/workflows/climpred_installs.yml
- .github/workflows/climpred_testing.yml
- .github/workflows/lint.yml
Fix stable branch also
-   [ ]  I have added docstrings to all new …
> Fix stable secrets

- climpred/bootstrap.py
- requirements.txt
> unfix numpy version

- CHANGELOG.rst
- ci/requirements/minimum-tests.yml
- climpred/classes.py
- climpred/smoothing.py
- climpred/tests/conftest.py
xesmf uses cf_xarray if lon or lat not in ds.coords.
Closes #543 #390 
-   [ ]  I …
> unfix xesmf 

- climpred/checks.py
- climpred/classes.py
- climpred/constants.py
- climpred/logging.py
- climpred/prediction.py
finishing up #566 
Please describe the tests that you ran to verify your …
> reference log, reference check

- .binder/environment.yml
- CHANGELOG.rst
- README.rst
- docs/source/index.rst
link: https://mybinder.org/v2/gh/pangeo-data/climpred/master?urlpath=lab%2Ftree%2Fdocs%2Fsource%2Fquick-start.ipynb
equiv from branch: https://mybinder.org/v2/gh/aaronspring/climpred/AS_binder_docs?urlpath=lab%2Ftree%2Fdocs%2Fsource%2Fquick-start.ipynb
Closes #549
> add binder env

- CHANGELOG.rst
- README.rst
- docs/source/contributing.rst
- docs/source/index.rst
If you have a local branch:
```
git branch -m master main
git fetch origin
git branch -u origin/main main
```
because its 2021. language defines reality.
> switch from master to main

- CHANGELOG.rst
- climpred/metrics.py
- climpred/tests/test_PerfectModelEnsemble_class.py
- climpred/tests/test_metrics_perfect.py
- docs/source/api.rst
- docs/source/api/climpred.metrics._roc.rst
- docs/source/metrics.rst
- requirements.txt
adds new metric from xs==0.0.19
-   [ ]  I have added docstrings to all new …
> Receiver Operating Characteristic (ROC)

- ci/requirements/climpred-dev.yml
- climpred/stats.py
> unpin pytest

- .github/workflows/climpred_testing.yml
- .github/workflows/upstream-dev-ci.yml
- CHANGELOG.rst
- ci/install-upstream-wheels.sh
- ci/requirements/climpred-dev.yml
runs every thursday and raises issue when found upstream version related issue
Closes #518 
Please describe the tests that you ran to verify your changes. This could point to a cell in the updated notebooks. Or a snippet of code with accompanying …
> upstream CI

- .github/workflows/climpred_testing.yml
- CHANGELOG.rst
- climpred/__init__.py
- climpred/bias_removal.py
- climpred/constants.py
- climpred/options.py
- climpred/reference.py
- climpred/tests/test_lead_time_resolutions.py
- climpred/tests/test_options.py
- climpred/utils.py
- docs/source/api.rst
- docs/source/api/climpred.options.set_options.rst
- docs/source/examples.rst
- docs/source/examples/NWP/NWP_GEFS_6h_forecasts.ipynb
- docs/source/examples/monseas/monthly-enso-subx-example.ipynb
- docs/source/examples/monseas/seasonal-enso-subx-example.ipynb
- docs/source/examples/subseasonal/daily-S2S-ECMWF.ipynb
- docs/source/examples/subseasonal/daily-subx-example.ipynb
- docs/source/examples/subseasonal/weekly-subx-example.ipynb
- docs/source/initialized-datasets.rst
- docs/source/setting-up-data.rst
Closes #600 #602 #404 #529 #587 
-   [x]  This change requires a documentation update
-   [x]  Improved Documentation
-   [x]  I have …
> allow shorter leads for numerical weather prediction

- CHANGELOG.rst
- climpred/checks.py
- climpred/classes.py
- climpred/constants.py
- climpred/tests/test_HindcastEnsemble_class.py
- docs/source/setting-up-data.rst
rename to climpred dims if coordinate standard_names matches
Closes #613
-   [x]  This change requires a documentation update
-   [x]  I have updated the sphinx documentation, if necessary.
http://cfconventions.org/Data/cf-standard-names/current/build/cf-standard-name-table.html
> rename from CF_standard_names

- ci/requirements/climpred-dev.yml
- ci/requirements/docs.yml
- ci/requirements/docs_notebooks.yml
- ci/requirements/minimum-tests.yml
Closes #621 
-   [x] versioning
> nc-time-axis unpin

- CHANGELOG.rst
- climpred/bias_removal.py
- climpred/checks.py
- climpred/classes.py
- climpred/metrics.py
- climpred/options.py
- climpred/tests/test_options.py
- climpred/utils.py
Closes #628 
-   [x]  I have updated the sphinx documentation, if necessary.
> silence climpred warnings via options

- CHANGELOG.rst
- climpred/classes.py
- climpred/tests/test_PredictionEnsemble.py
- climpred/tests/test_xarray_methods.py
`PredictionEnsemble` inherits many properties from xr.Dataset.
Closes #568
pytest
> PredictionEnsemble feels like xr.Dataset

- CHANGELOG.rst
> release 2.1.4

- .gitignore
- CHANGELOG.rst
- climpred/checks.py
- climpred/classes.py
- climpred/constants.py
- climpred/horizon.py
- climpred/tests/test_PredictionEnsemble.py
- requirements.txt
add CF metadata
Closes #639
-   [x]  Breaking change (fix or feature that would cause existing functionality to not work as expected)
- http://cfconventions.org/Data/cf-conventions/cf-conventions-1.8/cf-conventions.html
- https://cf-xarray.readthedocs.io/en/latest/generated/xarray.DataArray.cf.add_canonical_attributes.html#xarray.DataArray.cf.add_canonical_attributes
> attach metadata

- CHANGELOG.rst
- climpred/classes.py
- climpred/tests/test_PredictionEnsemble.py
- warn upon instantiation of `PredictionEnsemble` if `xskillscore` would raise chunking `ValueError`
- implement `PredictionEnsemble.chunks`
Closes #509 
-   [x]  Improved Error messages
-   [ ]  I have updated the sphinx documentation, if necessary.
-   [ ]  Any new functions are added to the API. (See contribution guide)
Please add any …
> _warn_if_chunked_along_init_member_time

- CHANGELOG.rst
- README.rst
- ci/install-upstream-wheels.sh
- docs/source/index.rst
> fix upstream-ci with new deps

- CHANGELOG.rst
- climpred/bias_removal.py
- climpred/classes.py
- climpred/prediction.py
- climpred/tests/test_bias_removal.py
- requirements.txt
use members as samples in xclim remove_bias methods
Follows on #667 
> use members as samples in xclim remove_bias methods

- CHANGELOG.rst
> release v2.1.6

- README.rst
- docs/source/index.rst
- requirements.txt
> Update versions in requirements.txt

- CHANGELOG.rst
- climpred/metrics.py
- climpred/tests/test_metrics.py
- docs/source/api.rst
- docs/source/api/climpred.metrics._less.rst
- docs/source/metrics.rst
new metric
Closes #239 
-   [ ]  I have commented my code, particularly in hard-to-understand areas.
-   [x]  I have updated the sphinx documentation, if necessary.
-   [x]  Any new functions are added to the API. (See contribution guide)
Kadow, C., Illing, S., Kunst, O., Rust, H. W., Pohlmann, H., Müller, W. A., & Cubasch, U. (2016). Evaluation of forecasts by accuracy and spread in the MiKlip decadal climate prediction system. Meteorologische Zeitschrift, 631–643. doi: 10/f9jrhw
> implement LESS

- CHANGELOG.rst
- ci/requirements/climpred-dev.yml
- climpred/bootstrap.py
- climpred/classes.py
- climpred/metrics.py
- climpred/options.py
- climpred/prediction.py
- climpred/reference.py
- climpred/tests/test_HindcastEnsemble_class.py
- climpred/tests/test_graphics.py
- climpred/tests/test_utils.py
- climpred/utils.py
Closes #475
-   [x]  Refactoring
> Refactor add_attrs into classes `verify()`

- .pre-commit-config.yaml
- CHANGELOG.rst
- climpred/bootstrap.py
- climpred/classes.py
- climpred/tests/test_utils.py
- climpred/utils.py
Closes #695
-   [x]  Improved Documentation
-   [ ]  Any new functions are added to the API. (See contribution guide)
> add `attrs` to new `coords`

- CHANGELOG.rst
- ci/requirements/climpred-dev.yml
- ci/requirements/docs.yml
- ci/requirements/docs_notebooks.yml
- ci/requirements/maximum-tests.yml
- ci/requirements/minimum-tests.yml
- climpred/tests/test_valid_time.py
- climpred/utils.py
- requirements.txt
Closes #698 
-   [x]  I have commented my code, particularly in hard-to-understand areas.
> fix `valid_time` `freq` bug

- CHANGELOG.rst
- climpred/tests/test_bootstrap.py
- climpred/tests/test_metrics.py
Closes #559 
-   [x]  Refactoring
> reduce skipped tests

- CHANGELOG.rst
- climpred/reference.py
- climpred/tests/test_reference.py
> Fix climatology `season` and `weekofyear`

- CHANGELOG.rst
- climpred/alignment.py
- climpred/bootstrap.py
- climpred/classes.py
- climpred/graphics.py
- climpred/metrics.py
- climpred/options.py
- climpred/reference.py
- climpred/tests/test_reference.py
- climpred/utils.py
- docs/source/api.rst
- docs/source/api/climpred.reference.compute_climatology.rst
- docs/source/api/climpred.reference.compute_persistence_from_first_lead.rst
- docs/source/metrics.rst
~~- [ ] for `HindcastEnsemble`?~~ due to `alignment`
~~- [ ] select `init`s from verif for persistence?~~
Closes #637 
-   [x]  I have commented my code, particularly in hard-to-understand areas.
-   [ ]  I have updated the sphinx documentation, if necessary.
-   [x]  Any new functions are added to the API. (See contribution guide)
> 🧷`persistence` with `initialized` `lead=0`

- climpred/tests/test_map.py
- climpred/tests/test_reference.py
test was written to strict
https://stackoverflow.com/questions/45671803/how-to-use-pytest-to-assert-no-warning-is-raised
> make warnings test less strict

- README.rst
- docs/source/index.rst
- readthedocs.yml
Faster rtd with mamba 
Precommit badge and precommit ci
> pre-commit ci

- .github/workflows/comment_binder_pr_link.yml
- climpred/classes.py
> fix `repr`

- docs/source/bias_removal.ipynb
> DOC: fix broken link

- CHANGELOG.rst
- climpred/classes.py
add valid_time and verify(dim=[]) example doctest
-   [x]  `doctest`
-   [ ]  CHANGELOG is updated with reference to this PR.
> add `valid_time` in `plot_alignment(return_xr=True)`

- .github/workflows/upstream-dev-ci.yml
make reports post issues when scheduled
> upstream CI posts issues

- .github/workflows/climpred_testing.yml
> extend CI to python3.10

- CHANGELOG.rst
- README.rst
- docs/source/index.rst
> Release 2.3.0

- .pre-commit-config.yaml
- CHANGELOG.rst
less often pre-commi\t autoupdate
> pre-commit autoupdate_schedule quarterly

- .github/workflows/climpred_testing.yml
- .pre-commit-config.yaml
- ci/requirements/docs.yml
- ci/requirements/minimum-tests.yml
- docs/source/conf.py
- requirements.txt
* Update requirements.txt
* Update requirements.txt
* Update docs.yml
* Update .pre-commit-config.yaml
* Update climpred_testing.yml
* Update minimum-tests.yml
* Update climpred_testing.yml
* Update conf.py
-   [ ]  Performance (if you modified existing code run `asv` to detect performance changes) …
> Pin xarray version (#818)

- CHANGELOG.rst
Closes #839 
-   [x]  Improved Documentation
-   [ ]  CHANGELOG is updated with reference to this PR.
> Prepare v2.4.0
