climpred/stats.py

Found a bug with reordering the dimensions in `xr_rm_poly`. Have to temporarily delete the coordinates so that renaming doesn't throw an error. Use deep copy of datasets to avoid permanently altering them.

Fix polynomial removal

---

climpred/stats.py
climpred/tests/test_stats.py

Now handles xr.Dataset for xr_rm_poly and better exception message if dim doesn't exist
https://github.com/bradyrx/climpred/issues/91
https://github.com/bradyrx/climpred/issues/93
- [ x ] Bug fix (non-breaking change which fixes an issue)
- [ x  ] New feature (non-breaking change which adds functionality)
Added tests/test_stats.py
Saved the values before refactoring, and compared with the values after refactor from DPLE_hindcast_prediction notebook:
Also tried performing on multi-dim Dataset and xr.DataArray
```
import xarray as xr
import climpred as cp
ds = xr.tutorial.open_dataset('air_temperature')
ds = ds.assign(**{'airx2': ds['air'] * 2})
cp.stats.xr_rm_trend(ds['air'])
cp.stats.xr_rm_trend(ds)
```
- [n/a ] I have added …

Refactor xr rm poly

---

climpred/utils.py

Fixes https://github.com/bradyrx/climpred/issues/146
-   [  x ]  Bug fix (non-breaking change which fixes an issue)
`import climpred as cp`
`help(cp.stats.autocorr)`
```
Help on function autocorr in module climpred.stats:
autocorr(ds, lag=1, dim='time', return_p=False)
Calculate the lagged correlation of time series.
Args:
ds (xarray object): Time series or grid of time series.
lag (optional int): Number of time steps to lag correlate to.
dim (optional str): Name of dimension to autocorrelate over.
return_p (optional bool): If True, return correlation coefficients
and p …
```

Fix help() for decorated functions

---

.coveralls.yml
.travis.yml
README.md

Another attempt at installing a test coverage utility. Tested on my laptop locally and this one seems to work (https://coveralls.io/builds/23662285). Ran once, then added a simple test for `corr` from stats and it reflected that change, so this looks promising.
If this works, will  add a coveralls badge instead and remove codecov.

test coveralls as test coverage

---

climpred/classes.py

Improve exception msgs for various checks.
I use 'Some string' rather than """Some string""" because """ keeps the indentation and it's ugly to me in warning messages.
https://github.com/bradyrx/climpred/issues/150

Update exception msgs

---

climpred/classes.py
climpred/prediction.py

Deletes the predictability horizon function from `climpred` for the v1 release. We discussed that it would be better to formalize for v2.
Fixes https://github.com/bradyrx/climpred/issues/159

Remove predictability horizon for v1

---

.pre-commit-config.yaml

Adds hooks to disallow users (mainly collaborators and administrator) from pushing directly to master. Also checks that `pdb` and other debuggers aren't left in code. And that nobody is adding files with merge commits still lingering.

don't allow anyone to push to master directly

---

climpred/__init__.py
climpred/versioning/print_versions.py
requirements.txt
setup.cfg
setup.py

Uses `setuptools_scm` and follows `esmlab` conventions to allow a smart version to be printed for `climpred.` Follows suggestions from @andersy005.
Fixes https://github.com/bradyrx/climpred/issues/133
Upon pip install, you see a version:
Upon import, you can run `climpred.__version__`:
This currently says 0.0 since I don't have any formal tags/releases set up. The post573 is the number of commits we have here (with the extra layered ones from this PR).

Print version feature

---

climpred/prediction.py
climpred/tests/test_hindcast_prediction.py

Now `compute_uninitialized` automatically reduces the uninitialized ensemble and reference to the same time frame for one lead year. It also gives the option to return for a set number of `nlags`.
Fixes https://github.com/bradyrx/climpred/issues/186
-   [X]  Bug fix (non-breaking change which fixes an issue)
Small update to `pytest` to include the `nlags` argument. Simple test in notebook:
-   [X]  I have added docstrings to all new functions.
-   [X]  I have commented my code, particularly in hard-to-understand areas
-   [X]  Tests added for `pytest`, if necessary.
-   [X]  I have rebased onto master or develop (wherever I am merging) and dealt with any conflicts.
-   [X]  I have squashed commits to a reasonable amount, and force-pushed the …

Update compute uninitialized 

---

CHANGELOG.rst
ci/environment-dev-3.6.yml
requirements.txt

Quick fix to force version 0.0.4 of `xskillscore` on climpred to avoid `ImportError` from needing the newer probabilistic metrics.
Fixes https://github.com/bradyrx/climpred/issues/203
-   [X]  Bug fix (non-breaking change which fixes an issue)

Fix xskillscore version

---

CHANGELOG.rst
climpred/prediction.py
climpred/tests/test_hindcast_prediction.py
climpred/tests/test_perfect_model_prediction.py

This PR makes minor fixes to ensure that a lead-0 setup works. I.e., if you have a lead time starting with zero instead of one.
* Adds lead0/lead1 tests for perfect model, hindcast, and persistence.
* Removes `nlags` argument for uninitialized (this seems like something the user can handle broadcasting forward. Especially since we don't know what leads to attach to it)
* Adds lines to `compute_persistence` to handle a case where it receives a lead 0 starting time series
* Adds lead0/lead1 compatability to `compute_hindcast`
-   [X]  Bug fix (non-breaking change which fixes an issue)
**Hindcast**:
**Perfect Model**:
**Persistence**:
-   [X]  I have commented my code, particularly in hard-to-understand areas
-   [X]  Tests added for `pytest`, if …

Fix lead zero calculations

---

.travis.yml
CHANGELOG.rst
requirements.txt
setup.py

This adds matplotlib as a main dependency. Currently it is listed as an optional dependency under `.graphics` installation. But since it is imported in one of our main modules, `import climpred` breaks if the standard pip installation is used. (This was pointed out as I was setting up our conda installation here https://github.com/conda-forge/staged-recipes/pull/8822).

add matplotlib as a main dependency

---

ci/docs.yml

Adds `bottleneck` to docs environment so readthedocs can build.

add bottleneck for docs

---

CHANGELOG.rst
ci/environment-dev-3.6.yml
docs/source/index.rst
docs/source/scope.rst

This PR adds the scope of `climpred` to our docs, as reviewed by some of the developers and contributors. This will help future developers and users see the long-term vision of the package and avoid scope creep in implementing new features.

Add scope to docs

---

CHANGELOG.rst
asv_bench/asv.conf.json
asv_bench/benchmarks/__init__.py
asv_bench/benchmarks/benchmarks_perfect_model.py
ci/environment-dev-3.6.yml

`asv` benchmarking implemented. See https://asv.readthedocs.io/en/stable/using.html.
-   [ ]  How and where to host benchmarks? `xarray` hosts with `pandas` see https://raw.githubusercontent.com/pydata/xarray/master/README.rst
-   [ ]   Who runs benckmarks? just one person or many? do we write different benchmarks to use for supercomputers like mistral or chayenne? Can we include `asv` into CI?
-   [ ]   What are functions to be benchmarked? `compute_` and `bootstrap_`, but probably one metric might be enough for bootstrapping
- we will be aware of performance drops after commits
- we can optimize time and memory consumption of `compute_` and `bootstrap_`
- reduce time and peakmem of `compute_` and `bootstrap_`
-   [x]  New feature …

Implementation of `asv` benchmarking

---

docs/requirements.txt
requirements.txt

Quick PR to add `tqdm` to the main requirements and docs requirements since it isn't an optional package currently. "latest" docs is breaking right now because of this and `readthedocs` doesn't have a means to test out PRs just yet. This slipped through the cracks since we run `make html` from the dev branch, which has `tqdm` and `readthedocs` looks at `docs/requirements.txt`.

add tqdm to docs and main requirements

---

CHANGELOG.rst
ci/environment-dev-3.6.yml
climpred/bootstrap.py
climpred/prediction.py
climpred/stats.py
climpred/tests/test_hindcast_prediction.py
climpred/tests/test_perfect_model_prediction.py
climpred/tests/test_stats.py
climpred/tests/test_utils.py
climpred/tests/test_versioning.py
climpred/utils.py
docs/source/examples/tropical-pacific-ssts.ipynb
requirements.txt
setup.cfg

with CMIP6 we will handle quite large datasets. chunking with `dask` will faciliate this. However, we didn't test our `compute_x` and `stats` functions for this yet. Chunking across spatial dims always works out of the box. To be implemented is support for `compute_hindcast` with inputs chunked along `CLIMPRED_DIMS`. This could be connected to https://github.com/bradyrx/climpred/issues/237
Added:
- test compute_x dask
- test stats dask (skipped right now for `decorrelation_time`)
- tqdm.auto
- keep coords in `compute_hindcast`
Reworked:
- `var_weighted_mean_period`: now takes power_spectrum from `xrft`. much more powerful and no new base dependencies (`xrft` relies on what we use anyways). and now `dim` instead of `time_dim`. coords kept.
- `ddp`: dim='time'
Fixes # …

add dask tests

---

docs/requirements.txt

Adds `toolz` to the docs requirement. The main `readthedocs` broke due to not having this for some reason...
I got `climpred` signed up for beta testing to have `readthedocs` run on PRs. So I'm going to leave this open to see if it builds on the PR.

add toolz to docs requirement

---

.gitignore
CHANGELOG.rst
ci/environment-dev-3.6.yml
climpred/tests/test_hindcastEnsemble_class.py
requirements.txt

Updates `xskillscore` version to 0.0.9 to deal with NaN issues in `pearson_r_p_value`.

Update xskillscore version

---

CHANGELOG.rst
docs/source/helpful-links.rst
docs/source/index.rst
docs/source/publications.rst

Minor updates to documentation. This adds a "publications" page to place citations that used `climpred` and a "helpful links" page to curate good resources for initialized prediction analysis.
Addresses https://github.com/bradyrx/climpred/issues/254.

add helpful links and publications page to docs

---

CHANGELOG.rst
docs/source/index.rst

`climpred` v.1.2.0 includes a few exciting updates:
1. Users can now pass custom `metric` and `comparison` to their compute functions. This was made possible by @aaronspring reworking the code into a class-based system.
2. A set of new deterministic variables are now available (@aaronspring):
* Spearman ranked correlation
* Mean Absolute Deviation
* Mean Absolute Percent Error
* Symmetric Mean Absolute Percent Error
3. Users can now apply arbitrary `xarray` methods to the `PredictionEnsemble` objects (e.g. `.isel()`, `.sum()` and so on. (@bradyrx)
Along with a host of other bug fixes, minor additions, and a large expansion of documentation.

Release v1.2.0

---

climpred/bootstrap.py
climpred/checks.py
climpred/comparisons.py
climpred/constants.py
climpred/graphics.py
climpred/metrics.py
climpred/prediction.py
climpred/tests/test_comparisons.py
climpred/tests/test_compute_dims.py
climpred/tests/test_effective_p_value.py
climpred/tests/test_hindcast_prediction.py
climpred/tests/test_metrics.py
climpred/tests/test_perfect_model_prediction.py
climpred/tests/test_probabilistic.py
climpred/tests/test_utils.py
climpred/utils.py

Problem:
- `metrics` imported `CLIMPRED_DIMS` from `constants` but `constants` also imported `__ALL_METRICS__` from `metrics`
- same goes for `comparisons`
Solution:
- `ALL_METRICS` loop inside `metrics`, same for `comparison`
Downside:
- `constants` gets rather empty
- more import lines typically needed in all modules
Fixes # couple of #TODO's in the code
refactor
pytest
-   [ ]  I have squashed commits to a reasonable amount, and force-pushed the squashed commits.
Please add any references to manuscripts, textbooks, etc.

remove circular dependencies

---

CHANGELOG.rst
HOWTOCONTRIBUTE.rst
climpred/tests/conftest.py
climpred/tests/test_checks.py
climpred/tests/test_comparisons.py
climpred/tests/test_compute_dims.py
climpred/tests/test_demo_data.py
climpred/tests/test_effective_p_value.py
climpred/tests/test_graphics.py
climpred/tests/test_hindcastEnsemble_class.py
climpred/tests/test_hindcast_prediction.py
climpred/tests/test_metrics.py
climpred/tests/test_perfectModelEnsemble_class.py
climpred/tests/test_perfect_model_prediction.py
climpred/tests/test_probabilistic.py
climpred/tests/test_relative_entropy.py
climpred/tests/test_smoothing.py
climpred/tests/test_stats.py
climpred/tests/test_utils.py
climpred/tests/test_versioning.py
climpred/tests/test_xarray_methods.py

Problem: 
- we duplicate code in `tests`
- identical fixtures have different names in different files
Solution:
- pytest.fixtures are refactored into `conftest.py` which pytest automatically includes, see https://docs.pytest.org/en/latest/fixture.html
- docstrings added to each fixture
Benefit:
- cleaner testing code
- testing of fixtured class objects
Fixes #306 
refactor
pytest
-   [ ]  I have squashed commits to a reasonable amount, and force-pushed the squashed commits.
Please add any references to …

pytest refactor

---

CHANGELOG.rst
climpred/classes.py
climpred/prediction.py
climpred/tests/conftest.py
climpred/tests/test_effective_p_value.py
climpred/tests/test_hindcastEnsemble_class.py
climpred/tests/test_lead_time_resolutions.py
climpred/tests/test_logging_hindcast.py
climpred/utils.py

- logging to check which times are verified at each lead
- for now only checks years. otherwise use xr.cftime.shift
- implement common to `compute_hindcast`:
- missing: `verif`
- add logging examples to verification docs
resources
----------
- https://docs.pytest.org/en/latest/logging.html
- https://realpython.com/python-logging/
Use #318 
Please describe the tests that …

logging to verify different verification schemes in compute hindcast

---

.coveralls.yml
.travis.yml

Removes the `coveralls.yml` file with our token, since that's not supposed to be public (https://stackoverflow.com/questions/39501417/how-can-i-connect-coveralls-and-travis-in-github). Travis should be able to handle connecting to coveralls, since we're a public repo.

Remove coveralls token

---

CHANGELOG.rst
ci/environment-dev-3.6.yml
climpred/bootstrap.py
climpred/reference.py
climpred/tests/conftest.py
climpred/tests/test_bootstrap.py
climpred/utils.py
requirements.txt

- lead=-1 changed
- persistence: keep_attrs
- reimplement `xr.quantile`
- I had to `introduce rechunk_to_single_chunk_if_more_than_one_chunk_along_dim`, because we had this in `my_quantile`, see I tried to re-implement:
https://github.com/bradyrx/climpred/blob/8be0a8939b15d248939b4aa45244a0d9617af290/climpred/bootstrap.py#L58-L62 This maybe have triggered some calculations. I now reimplemented as is and therefore got rid of `my_quantile` and put this piece before `xr.quantile
Closes #316 
-   [ ]  I have squashed commits to a reasonable amount, and force-pushed the squashed commits.

make fit for xr=0.15.1

---

.github/ISSUE_TEMPLATE.md
CHANGELOG.rst
ci/environment-dev-3.6.yml
requirements.txt

This enforces `cftime` version `1.1.2` which was released yesterday and optimizes `cftime` objects, getting 200-400x speedups on some of their basic functions. This will work in hand with our bootstrap optimizations to make `climpred` faster. This will speed up the base operations, while our bootstrap changes will make `dask` easier to handle.
See my issue at `cftime` on speedups: https://github.com/Unidata/cftime/issues/158.
-   [X]  Performance (if you touched existing code run `asv` to detect performance changes)
-   [X]  refactoring

Enforce most recent cftime version

---

climpred/metrics.py

Quick docs fix, showing that MAPE maximum is infinity. 
Closes https://github.com/bradyrx/climpred/issues/359

fix typo in MAPE docs

---

CHANGELOG.rst

Updates CHANGELOG for version `2.1.0` release. Going to release this as `2.1.0.post1` per https://www.python.org/dev/peps/pep-0440/#post-releases since I accidentally release 2.1.0 on PIP before cleaning up the CHANGELOG.

Version 2.1.0.post1

---

CHANGELOG.rst
climpred/classes.py
climpred/tests/conftest.py
climpred/tests/test_hindcastEnsemble_class.py
climpred/tests/test_perfectModelEnsemble_class.py

add metric_kwargs to PredictionEnsemble methods
Closes #386 
pytest
-   [x]  I have squashed commits to a reasonable amount, and force-pushed the squashed commits.

add metric_kwargs to PredictionEnsemble methods

---

README.rst
docs/source/index.rst

HackMD just added a badge, so you can link to a collaborative markdown note. I thought it'd be nice to have a badge to a note where we sketch out a continuously updated roadmap. This would sort of triage the issues and also sketch out long-term ideas and rank them in priority order.
Let me know what happens when you click the badge @aaronspring / @ahuang11 / @raybellwaves. I'm curious if anyone can just come in and overwrite/delete everything or if there's some level of accepting changes.

Add HackMD badge to docs and readme

---

ci/environment-dev-3.6.yml

`black` has been breaking on all of our Travis builds since they recently released a new version that relies upon `dataclasses`. Not sure why that didn't get installed with the recent update, but I just added it as a dev requirement.

Fix black travis

---

.github/workflows/climpred_testing.yml

Tries adding `pull_request_target` to github actions to give permission to forked PRs.
to do:
1. See how this affects the tests launched here on the main branch
2. Open PR on forked branch and see if tests run there
3. Ensure that tests aren't run against master (like previously with `pull_request`). Can purposefully break a test on the branch and see.
4. Push something else to the branch and make sure tests re-run.

try pull_request_target

---

.github/workflows/climpred_installs.yml
.github/workflows/climpred_testing.yml
.github/workflows/lint.yml

Codecov is the only thing breaking now on CI. We can't upload to it. See https://github.com/codecov/codecov-action/issues/43.

try updating codecov

---

climpred/classes.py
docs/source/alignment.ipynb
docs/source/examples/decadal/Significance.ipynb
docs/source/examples/decadal/diagnose-potential-predictability.ipynb
docs/source/prediction-ensemble-object.ipynb
docs/source/quick-start.ipynb

Fixes small bug for `HindcastEnsemble.verify()` to label `init` now `initialized`.

fix labeling of hindcast initialized

---

.github/workflows/climpred_testing.yml
ci/requirements/minimum-tests.yml
climpred/tests/conftest.py

This PR attempts to speed the CI setup by using mamba for conda environment creation. 
Please describe the tests that you ran to verify your changes. This could point to a cell in the updated notebooks. Or a snippet of code with accompanying figures …

Use mamba + pytest-xdist to speed up CI testing

---

CHANGELOG.rst
climpred/prediction.py
climpred/tests/conftest.py
climpred/tests/test_HindcastEnsemble_class.py

allow multiple types for dim: str, list of str, tuple of str, set of str, user is encouraged to use str or list of str as in docstrings mentioned already before
also rm coords fix in conftest, which is not needed after #543 which changed coords in climpred-data
Closes #519 …

allow multiple types for dim

---

.github/workflows/climpred_installs.yml
.github/workflows/climpred_testing.yml
.github/workflows/lint.yml
CHANGELOG.rst
ci/requirements/climpred-dev.yml
ci/requirements/docs.yml
ci/requirements/docs_notebooks.yml
ci/requirements/minimum-tests.yml
setup.py

drop py 3.6 support as xarray and numpy did. Climpred likely still works for py36 but py37 and above is encouraged and py36 related bugs will likely not be fixed

Drop py 3.6

---

.github/workflows/climpred_testing.yml
ci/requirements/climpred-dev.yml
ci/requirements/docs.yml
ci/requirements/docs_notebooks.yml
ci/requirements/minimum-tests.yml
climpred/tests/test_HindcastEnsemble_class.py
climpred/tests/test_PerfectModelEnsemble_class.py
climpred/tests/test_bootstrap.py
climpred/tests/test_metrics_perfect.py
climpred/tests/test_probabilistic.py
climpred/tests/test_uninitialized.py
climpred/tutorial.py

speed up tests

---

climpred/tests/test_horizon.py
requirements.txt

upstream fix: https://github.com/xarray-contrib/xskillscore/pull/309, here temporary for `main`, next release earliest once `xs` is patched

fix xr < 0.18

---

ci/requirements/climpred-dev.yml
ci/requirements/docs.yml
ci/requirements/docs_notebooks.yml
ci/requirements/minimum-tests.yml
climpred/bootstrap.py
requirements.txt

make installable and tests passing from source
Closes #618 #604
https://github.com/SciTools/nc-time-axis/pull/59
https://github.com/SciTools/nc-time-axis/issues/58

unfix xarray, use nc-time-axis branch utime fix

---

CHANGELOG.rst
ci/requirements/climpred-dev.yml
ci/requirements/docs.yml
ci/requirements/docs_notebooks.yml
ci/requirements/minimum-tests.yml
climpred/bootstrap.py
climpred/checks.py
climpred/tests/test_HindcastEnsemble_class.py
climpred/tests/test_checks.py
requirements.txt

allow more dims in initialized than in observations, very useful for multi-model study with single observation product
Closes #129 #528 

allow model dim in initialized when not in obs

---

climpred/alignment.py
climpred/reference.py
climpred/tests/test_HindcastEnsemble_class.py
requirements.txt

comment was misleading. alignment already takes care of alignment via `all_verifs`
Closes #586
Fix `xclim==0.29`
fix plot(x='time') works as default
-   [ ]  Performance (if you modified existing code run `asv` to detect performance changes)
-   [ ]  Improved Documentation
-   [ ]  I have commented my code, particularly in hard-to-understand areas.
-   [ ]  I have updated the sphinx …

add tests to show #586 can be closed

---

CHANGELOG.rst
climpred/classes.py
climpred/tests/test_HindcastEnsemble_class.py
climpred/tests/test_PerfectModelEnsemble_class.py
climpred/tests/test_metrics.py

Verify_groupby

---

CHANGELOG.rst
ci/requirements/climpred-dev.yml
ci/requirements/docs.yml
ci/requirements/maximum-tests.yml
ci/requirements/minimum-tests.yml
climpred/classes.py
climpred/tests/test_repr.py
requirements.txt
setup.py

- `IPython.display.display` wont work after upgrade
- actually not needed with `_repr_html` https://ipython.readthedocs.io/en/stable/config/integrating.html

rm `IPython`

---

CHANGELOG.rst
climpred/alignment.py
climpred/classes.py
climpred/tests/test_alignment.py
climpred/tests/test_bias_removal.py

- `xr.DataArray.coords['init'].isin(xr.DataArray.coords['time'])` is slow
- dont use `isin` on `xr.CFTimeIndex`-backed `xr.DataArray` but after converting to index and `asi8` (e.g. 'ms since 1970')
Closes #414 
-   [x]  Performance (if you modified existing code run `asv` to detect performance changes)
-   [x]  Refactoring

`isin` on `asi8` instead of `cftime`

---

CHANGELOG.rst
climpred/classes.py
climpred/reference.py
climpred/tests/test_reference.py

fix `set_options(PerfectModel_persistence_from_initialized_lead_0=True)` multiple `reference` bug

---

.github/workflows/comment_binder_pr_link.yml
climpred/utils.py

resolve `ImportError` when installed `climpred` from `conda`. didnt break when installed via `pip`
```python
def add_attrs_to_climpred_coords(results):
"""Write attrs for coords added by climpred."""
>       from . import __version__ as version
E       ImportError: cannot import name '__version__' from 'climpred'
```

resolve `ImportError` for `version`

---

CHANGELOG.rst
climpred/classes.py
climpred/tests/test_alignment.py

relates to #775 
-   [x]  I have commented my code, particularly in hard-to-understand areas.

`alignment=same_verifs` `valid_time` should not contains any `NaN`

---

CHANGELOG.rst
climpred/classes.py
climpred/tests/test_bias_removal.py

`CLIMPRED_ENSEMBLE_DIMS` shouldnt be dropped
Closes #771 

fix single `lead` dim not dropped in `remove_bias`

---

CHANGELOG.rst
docs/source/contributors.rst
docs/source/initialized-datasets.rst

Signed-off-by: Trevor Gamblin <tvgamblin@gmail.com>
Noticed that the website link for the GEFS database returns a 404. Found the new URL and replaced the old one.
-   [*]  Improved Documentation
N/A
N/A

Fix broken GEFS link

---

requirements.txt

The doctests fail because pooch is missing. It was probably removed as a required dependency in one of your dependencies. I add it to requirements.txt because you have cf-xarray as core dependency (could be debated). Let's see if this gets the tests to run...
(xref conda-forge/climpred-feedstock#26 - more PRs may come)
-   [ ]  Performance (if you modified existing code run `asv` to detect performance changes)
-   [ ]  Improved Documentation
-   [ ]  Tests added for …

require pooch

---

ci/requirements/maximum-tests.yml
ci/requirements/minimum-tests.yml
climpred/classes.py
climpred/metrics.py
climpred/reference.py
climpred/tests/test_options.py
climpred/tests/test_probabilistic.py
requirements.txt

After #830 we can check if what happens if we unpin xarray (we can still add a lower pin later)
supports https://github.com/conda-forge/climpred-feedstock/issues/26 
xclim in #832 
-   [x]  unpin dependencies
-   [x]  Tests added for `pytest` except for `xclim`
-   [ ]  CHANGELOG is updated with reference to this PR.

unpin xarray

---

CHANGELOG.rst
HOWTORELEASE.rst
ci/requirements/docs.yml
docs/source/alignment.ipynb
docs/source/api.rst
docs/source/api/climpred.bootstrap.bootstrap_compute.rst
docs/source/api/climpred.bootstrap.bootstrap_hindcast.rst
docs/source/api/climpred.bootstrap.bootstrap_perfect_model.rst
docs/source/api/climpred.prediction.compute_hindcast.rst
docs/source/conf.py
setup.py

This PR fixes a few issues with dependency conflicts that were causing the docs to fail to build, as well as address a few calls directly to now-obsolete functions.
There remains around 230 documentation build warnings, but nothing that breaks the build itself. Addressing all of these could take time.
-   [x]  Improved Documentation
Tested via ReadTheDocs
-   [x]  I have updated the sphinx documentation, if necessary.
See also: #844

Address several documentation warnings

---

.pre-commit-config.yaml
climpred/classes.py
climpred/prediction.py
climpred/preprocessing/shared.py
climpred/utils.py

Adds necessary typing for mypy-compliance
-   [x]  Breaking change (fix or feature that would cause existing functionality to not work as expected)
The breaking change is that the affected functions (with call signatures containing `*`) MUST now use keyword arguments to operate (entries can no longer be passed as positional arguments). I'm not sure how much of a breaking change this is for `climpred`, but if it is, I can mention that in the changelog.
Testing on GitHub Workflows
-   [ ]  CHANGELOG is updated with reference to this PR.
https://github.com/python/mypy/issues/9091

No longer allow implicit optional (mypy)

---

.pre-commit-config.yaml
CHANGELOG.rst
ci/requirements/climpred-dev.yml
ci/requirements/docs.yml
ci/requirements/maximum-tests.yml
ci/requirements/minimum-tests.yml
climpred/bootstrap.py
climpred/classes.py
climpred/conftest.py
climpred/tests/test_bias_removal.py
climpred/tests/test_lead_time_resolutions.py
climpred/utils.py
requirements.txt

* Adds a pin on `importlib-metadata` which is needed for `esmpy ==8.4`.
* Raises the minimum version of `numpy` to v1.25.0
* Sets an absolute minimum `xarray` version (0.19.0) and a pinned version based on `xclim`'s `xarray` needs (2022.6.0) 
* Addresses a few small `DeprecationWarnings`
Some things that should be determined:
* It appears that the `mpi`-based Anaconda builds of `esmpy` are no longer being produced (dropped after `esmpy` >=8.4). Do we still want to only be testing against this build configuration explicitly?
* The `minimum` dependencies build is failing because nothing is preventing the installation of `numpy>=2.0.0` (and I imagine that this is incompatible with `cf-xarray`, hence the errors). Should we explicit pin dependencies below their next major version for this …

Pin importlib-metadata, raise numpy to v1.25, synchronize dependencies

---

CHANGELOG.rst

* Updates the release date in the changelog to today (2024-07-05)

Prepare v2.5.0

---

.pre-commit-config.yaml

This change fixes issues with the `mypy` precommit check, specifically the replacement of the deprecated `types-pkg_resources` with `types-setuptools`.
https://pypi.org/project/types-pkg-resources/

update mypy pre-commit configuration, hooks
